apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rabbit
  template:
    metadata:
      labels:
        app: demo-rabbit
    spec:
      containers:
        - name: demo-rabbit
          image: ghcr.io/azratul/rabbit-project:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLUENTD_HOST
              value: "192.168.100.77"
            - name: FLUENTD_PORT
              value: "24224"
          envFrom:
            - secretRef: 
                name: mongo-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
